import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import CookiesProviderClient from '../components/CookiesProviderClient'
import useServerDarkMode from "@/hooks/use-server-dark-mode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const theme = useServerDarkMode();
  return (
    <html lang="en" className={theme}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CookiesProviderClient>
          <div className="mx-auto max-w-2xl p-6">
            <Header />          
            <main className="prose mt-12">            
              {children}            
            </main>          
          </div>
        </CookiesProviderClient>
      </body>
    </html>
  );
}